/*****************************************************************************************   
* MaxLinear, Inc. retains all right, title and interest (including all intellectual
* property rights) in and to this computer program, which is protected by applicable
* intellectual property laws.  Unless you have obtained a separate written license from
* MaxLinear, Inc. or an authorized licensee of MaxLinear, Inc., you are not authorized
* to utilize all or a part of this computer program for any purpose (including
* reproduction, distribution, modification, and compilation into object code), and you
* must immediately destroy or return all copies of this computer program.  If you are
* licensed by MaxLinear, Inc. or an authorized licensee of MaxLinear, Inc., your rights
* to utilize this computer program are limited by the terms of that license.
*
* This computer program contains trade secrets owned by MaxLinear, Inc. and, unless
* authorized by MaxLinear, Inc. in writing, you agree to maintain the confidentiality
* of this computer program and related information and to not disclose this computer
* program and related information to any other person or entity.
*
* Misuse of this computer program or any information contained in it may results in
* violations of applicable law.  MaxLinear, Inc. vigorously enforces its copyright,
* trade secret, patent, contractual, and other legal rights.
*
* THIS COMPUTER PROGRAM IS PROVIDED “AS IS” WITHOUT ANY WARRANTIES, AND MAXLINEAR, INC.
* EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES OF
* MERCHANTIBILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NONINFRINGEMENT.
****************************************************************************************
*                                        Copyright (c) 2012, MaxLinear, Inc.
****************************************************************************************/


#ifndef HOST_PROTOCOL_OPCODES_H
#define HOST_PROTOCOL_OPCODES_H


///////////////////////////////////////////////////////////////////////////////
// ENUM
///////////////////////////////////////////////////////////////////////////////
/*

typedef enum
{
    //Boot
    BCM_UW_COM_BOOT_HEADER_MSG_OPCODE_E,
    BCM_UW_COM_BOOT_DATA_MSG_OPCODE_E,
    BCM_UW_COM_BOOT_CHECKSUM_MSG_OPCODE_E,
    BCM_UW_COM_JUMP_TO_FW_MSG_OPCODE_E,
    BCM_UW_COM_VERSION_GET_OPCODE_E,
    BCM_UW_COM_DEV_CONFIG_FILE_LOAD_OPCODE_E,

    //Configuration
    BCM_UW_COM_LOAD_CONFIG_FILE_OPCODE_E,
    BCM_UW_COM_RUN_CONFIG_FILE_OPCODE_E,
    BCM_UW_COM_CONFIG_FILE_GET_DONE_OPCODE_E, //removed
    BCM_UW_COM_TX_RX_START_OPCODE_E,

    //Host-related and General
    BCM_UW_COM_ALARM_ENABLE_SET_OPCODE_E,
    BCM_UW_COM_ALARM_ENABLE_GET_OPCODE_E,
    BCM_UW_COM_ALARM_STATUS_GET_OPCODE_E,
    BCM_UW_COM_HOST_INFO_SET_OPCODE_E,
    BCM_UW_COM_HOST_INFO_GET_OPCODE_E,
    BCM_UW_COM_MAILBOX_MESSAGE_SEND_OPCODE_E,
    BCM_UW_COM_MAILBOX_MESSAGE_RECEIVE_OPCODE_E,
    BCM_UW_COM_TESTBUS_SET_OPCODE_E,
    BCM_UW_COM_INJECTION_SET_OPCODE_E,

    //Modem
    BCM_UW_COM_MODEM_STATUS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_ACQUIRE_COUNTERS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_FEC_COUNTERS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_IQ_IMBALANCE_STATUS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_EQUALIZER_STATUS_GET0_OPCODE_E,
    BCM_UW_COM_MODEM_EQUALIZER_STATUS_GET1_OPCODE_E,
    BCM_UW_COM_MODEM_ECHO_CANCELER_EQUALIZER_STATUS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_XPIC_STATUS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_RS_HIST_GET_OPCODE_E,
    BCM_UW_COM_MODEM_PREDISTORTION_COEFS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_PREDISTORTION_COEFS_SET_OPCODE_E,
    BCM_UW_COM_MODEM_PREDISTORTION_COEFS_EX_GET_OPCODE_E,
    BCM_UW_COM_MODEM_PREDISTORTION_COEFS_EX_SET_OPCODE_E,
    BCM_UW_COM_MODEM_PREEMPHASIS_COEFS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_PREEMPHASIS_COEFS_SET_OPCODE_E,
    BCM_UW_COM_MODEM_IQ_SAMPLES_REC_OPCODE_E,
    BCM_UW_COM_MODEM_IQ_SAMPLES_GET_OPCODE_E,
    BCM_UW_COM_ACQUIRE_START_OPCODE_E,
    BCM_UW_COM_PREAMBLE_SET_OPCODE_E,
    BCM_UW_COM_MODEM_TX_IQ_DELAY_SET_OPCODE_E,
    BCM_UW_COM_MODEM_RX_FREQ_OFFSET_SET_OPCODE_E,
    BCM_UW_COM_MODEM_TX_FREQ_OFFSET_SET_OPCODE_E,
    BCM_UW_COM_MODEM_DELAY_SET_OPCODE_E,
    BCM_UW_COM_MODEM_MUTE_SET_OPCODE_E,
    BCM_UW_COM_PROTECTION_STATUS_GET_OPCODE_E,
    BCM_UW_COM_PROTECTION_MODE_SET_OPCODE_E,
    BCM_UW_COM_PROTECTION_TX_RX_PHYID_SET_OPCODE_E,
    BCM_UW_COM_PROTECTION_RX_FORCE_SET_OPCODE_E,
    BCM_UW_COM_ACQUIRE_LOCK_CRITERIA_SET_OPCODE_E,

    //Modem Modes
    BCM_UW_COM_MODEM_MRC_STATUS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_MRC_COMBINER_EQU_STATUS_OPCODE_E,
    BCM_UW_COM_MODEM_MIMO_STATUS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_TX_OUTPUT_FILTER_SET_OPCODE_E,
    BCM_UW_COM_MODEM_TX_OUTPUT_FILTER_GET_OPCODE_E,
    BCM_UW_COM_MODEM_REPEATER_MODE_SET_OPCODE_E,
    BCM_UW_COM_MODEM_REPEATER_BAUD_SET_OPCODE_E,

    //Modem Filters
    BCM_UW_COM_ADPD_MODE_SET_OPCODE_E,
    BCM_UW_COM_ADPD_CALIB_START_OPCODE_E,
    BCM_UW_COM_ADPD_CALIB_GET_OPCODE_E,
    BCM_UW_COM_ECHO_CANCELER_DELAY_SET_OPCODE_E,
    BCM_UW_COM_ECHO_CANCELER_CALIB_START_OPCODE_E,
    BCM_UW_COM_ECHO_CANCELER_CALIB_GET_OPCODE_E,
    BCM_UW_COM_PVTMON_GET_OPCODE_E,

    //Diagnostic
    BCM_UW_COM_LOOPBACK_SET_OPCODE_E,
    BCM_UW_COM_DIG_CONFIGURE_OPCODE_E,
    BCM_UW_COM_DIG_CONFIGURE_EX_OPCODE_E,
    BCM_UW_COM_DIG_NOTCH_SET_OPCODE_E,

    //ACM
    BCM_UW_COM_ACM_COUNTERS_GET_OPCODE_E,
    BCM_UW_COM_ACM_CONFIGURATION_GET_OPCODE_E,
    BCM_UW_COM_ACM_THRESHOLD_SET_OPCODE_E,
    BCM_UW_COM_ACM_THRESHOLD_XPD_SET_OPCODE_E,
    BCM_UW_COM_ACM_THRESHOLD_GET_OPCODE_E,
    BCM_UW_COM_ACM_THRESHOLD_XPD_GET_OPCODE_E,
    BCM_UW_COM_ACM_PROFILE_ENABLE_OPCODE_E,
    BCM_UW_COM_ACM_PROFILE_MASK_GET_OPCODE_E,
    BCM_UW_COM_ACM_ENHANCED_ENGINE_MODE_SET_OPCODE_E,
    BCM_UW_COM_ACM_ENHANCED_ENGINE_MODE_GET_OPCODE_E,
    BCM_UW_COM_ACM_ENGINE_ENABLE_OPCODE_E,
    BCM_UW_COM_ACM_SWITCH_OPCODE_E,
    BCM_UW_COM_ACM_IMPROVE_OPCODE_E,
    BCM_UW_COM_ACM_GPM_DYNAMIC_ALLOCATION_SET_OPCODE,
    BCM_UW_COM_ACM_TX_POWER_GAIN_UPDATE_OPCODE_E,

    //Networking
    BCM_UW_COM_NET_FIXED_LATENCY_SET_OPCODE_E,
    BCM_UW_COM_PLA_STATUS_GET_OPCODE_E,
    BCM_UW_COM_PLA_ACM_SET_OPCODE_E,
    BCM_UW_COM_PLA_MODE_SET_OPCODE_E,
    BCM_UW_COM_PLA_FORCE_SET_OPCODE_E,
    BCM_UW_COM_PLA_COUNTERS_GET_OPCODE_E,
    BCM_UW_COM_PLA_COUNTERS_CLEAR_OPCODE_E,
    BCM_UW_COM_PLA_MSE_LIMIT_SET_OPCODE_E,
    BCM_UW_COM_PLA_PEER_DEVICE_SET_OPCODE_E,
    BCM_UW_COM_NET_FRAGMENTATION_SIZE_SET_OPCODE_E,
    BCM_UW_COM_NET_FRAGMENTATION_COUNTERS_GET_OPCODE_E,
    BCM_UW_COM_NET_FRAGMENTATION_COUNTERS_CLEAR_OPCODE_E,
    BCM_UW_COM_NET_MACFIFO_STATUS_GET_OPCODE_E,
    BCM_UW_COM_NET_8KHZ_MODE_SET_OPCODE_E,
    BCM_UW_COM_NET_8KHZ_DDS_OFFSET_GET_OPCODE_E, //removed

    //HC
    BCM_UW_COM_HC_ENGINE_ENABLE_OPCODE_E,
    BCM_UW_COM_HC_MASK_SET_OPCODE_E,
    BCM_UW_COM_HC_TYPE_SET_OPCODE_E,
    BCM_UW_COM_HC_LEARNING_AGEING_CONFIGURE_OPCODE_E,
    BCM_UW_COM_HC_DB_REFRESH_CONFIGURE_OPCODE_E,
    BCM_UW_COM_HC_DB_QUICK_FLUSH_OPCODE_E,
    BCM_UW_COM_HC_STATISTICS_GET_OPCODE_E,
    BCM_UW_COM_HC_PARSER_TYPE_SET_OPCODE_E,                          
    BCM_UW_COM_HC_PARSER_CLASS_ID_SET_OPCODE_E,

    //Peripherals
    BCM_UW_COM_GPIO_INT_CONFIG_OPCODE_E,
    BCM_UW_COM_GPIO_WRITE_OPCODE_E,
    BCM_UW_COM_GPIO_READ_OPCODE_E,
    BCM_UW_COM_AUXDAC_WRITE_OPCODE_E,
    BCM_UW_COM_AUXDAC_EXT_WRITE_OPCODE_E,
    BCM_UW_COM_AUXDAC_EXT_READ_OPCODE_E,
    BCM_UW_COM_AUXADC_READ_OPCODE_E,
    BCM_UW_COM_NET_ETH_PHY_REG_SET_OPCODE_E,
    BCM_UW_COM_NET_ETH_PHY_REG_GET_OPCODE_E,
    BCM_UW_COM_I2C_TRANSACTION_OPCODE_E,
    BCM_UW_COM_I2C_IS_TRANSACTION_COMPLETE_OPCODE_E, //removed
    BCM_UW_COM_SPI_TRANSACTION_OPCODE_E,
    BCM_UW_COM_SPI_IS_TRANSACTION_COMPLETE_OPCODE_E, //removed

    //Debug
    BCM_UW_COM_GENERAL_CONTROL_SET_OPCODE_E,
    BCM_UW_COM_GENERAL_CONTROL_GET_OPCODE_E,
    BCM_UW_COM_DEBUG_OPCODE_E,
    BCM_UW_COM_REGISTER_READ_OPCODE_E,
    BCM_UW_COM_REGISTER_WRITE_OPCODE_E,
    BCM_UW_COM_INTERNAL_OPCODE_E,

    //WideBand
    BCM_UW_COM_WB_RX_STATUS_GET_OPCODE_E,
    BCM_UW_COM_WB_TX_STATUS_GET_OPCODE_E,
    BCM_UW_COM_WB_RX_NCO_FREQ_SET_OPCODE_E,
    BCM_UW_COM_WB_TX_NCO_FREQ_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_IQ_DELAY_SET_OPCODE_E,
    BCM_UW_COM_WB_TXTX_SET_OPCODE_E,
    BCM_UW_COM_TX_TX_CALIB_STATUS_GET_OPCODE_E,
    BCM_UW_COM_TX_TX_CALIB_RESTART_OPCODE_E,
    BCM_UW_COM_WB_RX_IQMC_DELAY_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_IQMC_DELAY_GET_OPCODE_E,
    BCM_UW_COM_TRANSMITTER_MODE_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_SPECTRAL_INVERSION_SET_OPCODE_E,
    BCM_UW_COM_WB_SNAPSHOT_CONFIGURE_OPCODE_E,
    BCM_UW_COM_WB_SNAPSHOT_GET_OPCODE_E,

    BCM_UW_COM_WB_RX_AGC_STATUS_GET_OPCODE_E,
    BCM_UW_COM_WB_RX_AGC_GAIN_DIST_TABLE_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_AGC_DB_TO_DAC_TABLE_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_AGC_FREEZE_OPCODE_E,
    BCM_UW_COM_WB_RX_AGC_ROW_FORCE_OPCODE_E,

    BCM_UW_COM_WB_TX_AGC_STATUS_GET_OPCODE_E,
    BCM_UW_COM_WB_TX_AGC_CONFIGURE_OPCODE_E,
    BCM_UW_COM_WB_TX_AGC_TARGET_OPCODE_E,
    BCM_UW_COM_WB_TX_AGC_GAIN_DIST_TABLE_SET_OPCODE_E,
    BCM_UW_COM_WB_TX_AGC_DB_TO_DAC_TABLE_SET_OPCODE_E,
    BCM_UW_COM_WB_TX_AGC_ADC_TO_DBM_TABLE_SET_OPCODE_E,
    BCM_UW_COM_WB_TX_AGC_FREEZE_OPCODE_E,
    BCM_UW_COM_WB_TX_AGC_ROW_FORCE_OPCODE_E,

    //ETH Port
    BCM_UW_COM_ETH_PORT_INIT_OPCODE_E,
    BCM_UW_COM_ETH_PORT_FW_DOWNLOAD_OPCODE_E,
    BCM_UW_COM_ETH_PORT_CONFIGURE_OPCODE_E,
    BCM_UW_COM_ETH_PORT_STATUS_GET_OPCODE_E,
    BCM_UW_COM_ETH_PORT_COUNTERS_CLEAR_OPCODE_E,
    BCM_UW_COM_ETH_PORT_RX_COUNTERS_GET_OPCODE_E,
    BCM_UW_COM_ETH_PORT_TX_COUNTERS_GET_OPCODE_E,
    BCM_UW_COM_ETH_PORT_CLK_SET_OPCODE_E,

    //New 5.2
    BCM_UW_COM_DIG_PA_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_AGC_SETPOINT_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_AGC_BACKOFF_OFFSET_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_AGC_BANDWIDTH_SET_OPCODE_E,
    BCM_UW_COM_PPS_CALIB_START_OPCODE_E,
    BCM_UW_COM_PPS_CONFIGURE_OPCODE_E,
    BCM_UW_COM_MIMO_CONFIGURE_OPCODE_E,
    BCM_UW_COM_LONG_API_PROBE_OPCODE_E,
    BCM_UW_COM_MODEM_IQ_SAMPLES_EX_GET_OPCODE_E,
    BCM_UW_COM_NET_TXMAC_FIFO_IND_SET_OPCODE_E,
    BCM_UW_COM_DEV_CONFIG_RESULT_GET_OPCODE_E,
    BCM_UW_COM_PPS_OUTPUT_MODE_SET_OPCODE_E,
    BCM_UW_COM_TX_TX_DELAY_SET_OPCODE_E,
    BCM_UW_COM_TX_TX_MODE_SET_OPCODE_E,
    BCM_UW_COM_PPS_STATUS_GET_OPCODE_E,

    //New 5.4
    BCM_UW_COM_BER_COUNTERS_GET_OPCODE_E,
    BCM_UW_COM_BER_ENABLE_OPCODE_E,
    BCM_UW_COM_DEV_CONFIG_PARAM_MODIFY_OPCODE_E,
    BCM_UW_COM_DEV_CONFIG_START_OPCODE_E,
    BCM_UW_COM_XPIC_TO_FDD_SET_OPCODE_E,
    BCM_UW_COM_MIMO_DELAY_CALIB_START_OPCODE_E,
    BCM_UW_COM_MIMO_DELAY_CALIB_STATUS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_DELAY_GET_OPCODE_E,
    BCM_UW_COM_NET_ASYM_DELAY_GET_OPCODE_E,
    BCM_UW_COM_ADPD_GEAR_SHIFT_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_AGC_TABLE_OFFSET_SET_OPCODE_E,

    //New 5.5
    BCM_UW_COM_ASYMMETRY_CONFIG_EN_OPCODE_E,
    BCM_UW_COM_AVS_PROCESS_SET_OPCODE_E,
    BCM_UW_COM_AVS_STATUS_GET_OPCODE_E,
    BCM_UW_COM_AVS_REC_LVM_GET_OPCODE_E,
    BCM_UW_COM_ETH_PORT_FW_DOWNLOAD_HDR_OPCODE_E,
    BCM_UW_COM_ADPD_AUTO_MODE_CONFIGURE_OPCODE_E,
    BCM_UW_COM_ADPD_SYSTEM_FREEZE_OPCODE_E,
    BCM_UW_COM_ADPD_STATUS_GET_OPCODE_E,
    BCM_UW_COM_MODEM_IQ_SAMPLES_SOURCE_SET_OPCODE_E,
    BCM_UW_COM_DEV_CONFIG_STRING_PARAM_MODIFY_OPCODE_E,
    BCM_UW_COM_TXRXOP_STATUS_GET_OPCODE_E,

    //New 5.6
    BCM_UW_COM_XPIC_DELAY_CALIBRATION_START_OPCODE_E,
    BCM_UW_COM_XPIC_DELAY_CALIBRATION_STATUS_GET_OPCODE_E,
    BCM_UW_COM_MIMO_DIVERSITY_MUTE_SET_OPCODE_E,
    BCM_UW_COM_WB_RX_AGC_BACKOFF_COMPENSATION_SET_OPCODE_E,
    BCM_UW_COM_TX_RX_CTRL_SET_OPCODE_E,

    //New 5.7
    BCM_UW_COM_MODEM_RX_FREQ_LIMIT_SET_OPCODE_E,
    BCM_UW_COM_MRC_DELAY_CALIB_START_OPCODE_E,
    BCM_UW_COM_MRC_DELAY_CALIB_STATUS_GET_OPCODE_E,

    //-------
    //Flash
    //-------
    BCM_UW_COM_FLASH_HEADER_BURN_OPCODE_E,
    BCM_UW_COM_FLASH_HEADER_GET_OPCODE_E,
    BCM_UW_COM_FLASH_INFO_GET_OPCODE_E,
    BCM_UW_COM_FLASH_FW_ERASE_OPCODE_E,
    BCM_UW_COM_FLASH_FW_BURN_OPCODE_E,
    BCM_UW_COM_FLASH_FW_BURNEND_OPCODE_E,
    BCM_UW_COM_FLASH_FS_FORMAT_OPCODE_E,
    BCM_UW_COM_FLASH_FILECHUNK_PUT_OPCODE_E,
    BCM_UW_COM_FLASH_FILECHUNK_GET_OPCODE_E,
    BCM_UW_COM_FLASH_FILE_DELETE_OPCODE_E,
    BCM_UW_COM_FLASH_FILE_LIST_OPCODE_E,
    BCM_UW_COM_FLASH_FILE_SIZE_GET_OPCODE_E,

    //-------
    //DSP
    //-------
    BCM_UW_COM_DSP_BOOT_LOADER_SET_OPCODE_E,
    BCM_UW_COM_DSP_APP_LOAD_OPCODE_E,
    BCM_UW_COM_DSP_SUBSYSTEM_PER_DSP_CONFIG_OPCODE_E,
    BCM_UW_COM_DSP_BLOCK_CONFIG_OPCODE_E,
    BCM_UW_COM_DSP_START_OPCODE_E,
    BCM_UW_COM_DSP_STOP_OPCODE_E,
    BCM_UW_COM_DSP_DEBUG_SET_OPCODE_E,
    BCM_UW_COM_DSP_DEBUG_GET_OPCODE_E,
    BCM_UW_COM_DSP_APP_LOAD_DONE_OPCODE_E,
    BCM_UW_COM_DSP_MEM_WR_OPCODE_E,
    BCM_UW_COM_DSP_MEM_RD_OPCODE_E,
    BCM_UW_COM_DSP_MAILBOX_MESSAGE_SEND_OPCODE_E,
    BCM_UW_COM_DSP_MAILBOX_MESSAGE_RECEIVE_OPCODE_E,

    //-------
    //RF
    //-------
    BCM_UW_COM_RF_INTERNAL_CONTROL_OPCODE_E         = 240, //first RF opcode
    BCM_UW_COM_RF_ALL_INITIALIZE_OPCODE_E,
    BCM_UW_COM_RF_TX_STANDBY_SET_OPCODE_E,
    BCM_UW_COM_RF_TX_POWER_DOWN_OPCODE_E,
    BCM_UW_COM_RF_TX_ADPD_ENABLE_OPCODE_E,
    BCM_UW_COM_RF_TX_STATUS_GET_OPCODE_E,
    BCM_UW_COM_RF_RX_STANDBY_SET_OPCODE_E,
    BCM_UW_COM_RF_RX_POWER_DOWN_OPCODE_E,
    BCM_UW_COM_RF_RX_RSL_GET_OPCODE_E,
    BCM_UW_COM_RF_RX_STATUS_GET_OPCODE_E,
    BCM_UW_COM_RF_RX_TX_LOOPBACK_SET_OPCODE_E,
    BCM_UW_COM_RF_LO_SHARING_SET_OPCODE_E,
    BCM_UW_COM_RF_PROGRESS_ERROR_GET_OPCODE_E,
    BCM_UW_COM_RF_REGISTER_READ_OPCODE_E,
    BCM_UW_COM_RF_REGISTER_WRITE_OPCODE_E,

    //last one
    BCM_UW_COM_MAX_OPCODE_E,    //has to be <256

} BCM_UW_COM_OPCODE_ENUM;

*/


   //Boot
#define    BCM_UW_COM_BOOT_HEADER_MSG_OPCODE_E		  (0)
#define    BCM_UW_COM_BOOT_DATA_MSG_OPCODE_E		  (1)
#define    BCM_UW_COM_BOOT_CHECKSUM_MSG_OPCODE_E	  (2)
#define    BCM_UW_COM_JUMP_TO_FW_MSG_OPCODE_E		  (3)
#define    BCM_UW_COM_VERSION_GET_OPCODE_E			  (4)
#define    BCM_UW_COM_DEV_CONFIG_FILE_LOAD_OPCODE_E	  (5)

    //Configuration
#define    BCM_UW_COM_LOAD_CONFIG_FILE_OPCODE_E			(6)
#define    BCM_UW_COM_RUN_CONFIG_FILE_OPCODE_E			(7)
#define    BCM_UW_COM_CONFIG_FILE_GET_DONE_OPCODE_E 	(8)		//removed
#define    BCM_UW_COM_TX_RX_START_OPCODE_E				(9)

    //Host-related and General
#define    BCM_UW_COM_ALARM_ENABLE_SET_OPCODE_E			(10)
#define    BCM_UW_COM_ALARM_ENABLE_GET_OPCODE_E			(11)
#define    BCM_UW_COM_ALARM_STATUS_GET_OPCODE_E			(12)
#define    BCM_UW_COM_HOST_INFO_SET_OPCODE_E			(13)
#define    BCM_UW_COM_HOST_INFO_GET_OPCODE_E			(14)
#define    BCM_UW_COM_MAILBOX_MESSAGE_SEND_OPCODE_E		(15)
#define    BCM_UW_COM_MAILBOX_MESSAGE_RECEIVE_OPCODE_E	(16)
#define    BCM_UW_COM_TESTBUS_SET_OPCODE_E				(17)
#define    BCM_UW_COM_INJECTION_SET_OPCODE_E			(18)

    //Modem
#define    BCM_UW_COM_MODEM_STATUS_GET_OPCODE_E								  (19)
#define    BCM_UW_COM_MODEM_ACQUIRE_COUNTERS_GET_OPCODE_E					  (20)
#define    BCM_UW_COM_MODEM_FEC_COUNTERS_GET_OPCODE_E						  (21)
#define    BCM_UW_COM_MODEM_IQ_IMBALANCE_STATUS_GET_OPCODE_E				  (22)
#define    BCM_UW_COM_MODEM_EQUALIZER_STATUS_GET0_OPCODE_E					  (23)
#define    BCM_UW_COM_MODEM_EQUALIZER_STATUS_GET1_OPCODE_E					  (24)
#define    BCM_UW_COM_MODEM_ECHO_CANCELER_EQUALIZER_STATUS_GET_OPCODE_E		  (25)
#define    BCM_UW_COM_MODEM_XPIC_STATUS_GET_OPCODE_E						  (26)
#define    BCM_UW_COM_MODEM_RS_HIST_GET_OPCODE_E							  (27)
#define    BCM_UW_COM_MODEM_PREDISTORTION_COEFS_GET_OPCODE_E				  (28)
#define    BCM_UW_COM_MODEM_PREDISTORTION_COEFS_SET_OPCODE_E				  (29)
#define    BCM_UW_COM_MODEM_PREDISTORTION_COEFS_EX_GET_OPCODE_E				  (30)
#define    BCM_UW_COM_MODEM_PREDISTORTION_COEFS_EX_SET_OPCODE_E				  (31)
#define    BCM_UW_COM_MODEM_PREEMPHASIS_COEFS_GET_OPCODE_E					  (32)
#define    BCM_UW_COM_MODEM_PREEMPHASIS_COEFS_SET_OPCODE_E					  (33)
#define    BCM_UW_COM_MODEM_IQ_SAMPLES_REC_OPCODE_E							  (34)
#define    BCM_UW_COM_MODEM_IQ_SAMPLES_GET_OPCODE_E							  (35)
#define    BCM_UW_COM_ACQUIRE_START_OPCODE_E								  (36)
#define    BCM_UW_COM_PREAMBLE_SET_OPCODE_E									  (37)
#define    BCM_UW_COM_MODEM_TX_IQ_DELAY_SET_OPCODE_E						  (38)
#define    BCM_UW_COM_MODEM_RX_FREQ_OFFSET_SET_OPCODE_E						  (39)
#define    BCM_UW_COM_MODEM_TX_FREQ_OFFSET_SET_OPCODE_E						  (40)
#define    BCM_UW_COM_MODEM_DELAY_SET_OPCODE_E								  (41)
#define    BCM_UW_COM_MODEM_MUTE_SET_OPCODE_E								  (42)
#define    BCM_UW_COM_PROTECTION_STATUS_GET_OPCODE_E						  (43)
#define    BCM_UW_COM_PROTECTION_MODE_SET_OPCODE_E							  (44)
#define    BCM_UW_COM_PROTECTION_TX_RX_PHYID_SET_OPCODE_E					  (45)
#define    BCM_UW_COM_PROTECTION_RX_FORCE_SET_OPCODE_E						  (46)
#define    BCM_UW_COM_ACQUIRE_LOCK_CRITERIA_SET_OPCODE_E					  (47)

    //Modem Modes
#define    BCM_UW_COM_MODEM_MRC_STATUS_GET_OPCODE_E							  (48)
#define    BCM_UW_COM_MODEM_MRC_COMBINER_EQU_STATUS_OPCODE_E				  (49)
#define    BCM_UW_COM_MODEM_MIMO_STATUS_GET_OPCODE_E						  (50)
#define    BCM_UW_COM_MODEM_TX_OUTPUT_FILTER_SET_OPCODE_E					  (51)
#define    BCM_UW_COM_MODEM_TX_OUTPUT_FILTER_GET_OPCODE_E					  (52)
#define    BCM_UW_COM_MODEM_REPEATER_MODE_SET_OPCODE_E						  (53)
#define    BCM_UW_COM_MODEM_REPEATER_BAUD_SET_OPCODE_E						  (54)

    //Modem Filters
#define    BCM_UW_COM_ADPD_MODE_SET_OPCODE_E								  (55)
#define    BCM_UW_COM_ADPD_CALIB_START_OPCODE_E								  (56)
#define    BCM_UW_COM_ADPD_CALIB_GET_OPCODE_E								  (57)
#define    BCM_UW_COM_ECHO_CANCELER_DELAY_SET_OPCODE_E						  (58)
#define    BCM_UW_COM_ECHO_CANCELER_CALIB_START_OPCODE_E					  (59)
#define    BCM_UW_COM_ECHO_CANCELER_CALIB_GET_OPCODE_E						  (60)
#define    BCM_UW_COM_PVTMON_GET_OPCODE_E									  (61)

    //Diagnostic
#define    BCM_UW_COM_LOOPBACK_SET_OPCODE_E									  (62)
#define    BCM_UW_COM_DIG_CONFIGURE_OPCODE_E								  (63)
#define    BCM_UW_COM_DIG_CONFIGURE_EX_OPCODE_E								  (64)
#define    BCM_UW_COM_DIG_NOTCH_SET_OPCODE_E								  (65)

    //ACM
#define    BCM_UW_COM_ACM_COUNTERS_GET_OPCODE_E								  (66)
#define    BCM_UW_COM_ACM_CONFIGURATION_GET_OPCODE_E						  (67)
#define    BCM_UW_COM_ACM_THRESHOLD_SET_OPCODE_E							  (68)
#define    BCM_UW_COM_ACM_THRESHOLD_XPD_SET_OPCODE_E						  (69)
#define    BCM_UW_COM_ACM_THRESHOLD_GET_OPCODE_E							  (70)
#define    BCM_UW_COM_ACM_THRESHOLD_XPD_GET_OPCODE_E						  (71)
#define    BCM_UW_COM_ACM_PROFILE_ENABLE_OPCODE_E							  (72)
#define    BCM_UW_COM_ACM_PROFILE_MASK_GET_OPCODE_E							  (73)
#define    BCM_UW_COM_ACM_ENHANCED_ENGINE_MODE_SET_OPCODE_E					  (74)
#define    BCM_UW_COM_ACM_ENHANCED_ENGINE_MODE_GET_OPCODE_E					  (75)
#define    BCM_UW_COM_ACM_ENGINE_ENABLE_OPCODE_E							  (76)
#define    BCM_UW_COM_ACM_SWITCH_OPCODE_E									  (77)
#define    BCM_UW_COM_ACM_IMPROVE_OPCODE_E									  (78)
#define    BCM_UW_COM_ACM_GPM_DYNAMIC_ALLOCATION_SET_OPCODE					  (79)
#define    BCM_UW_COM_ACM_TX_POWER_GAIN_UPDATE_OPCODE_E						  (80)

    //Networking
#define    BCM_UW_COM_NET_FIXED_LATENCY_SET_OPCODE_E						  (81)
#define    BCM_UW_COM_PLA_STATUS_GET_OPCODE_E								  (82)
#define    BCM_UW_COM_PLA_ACM_SET_OPCODE_E									  (83)
#define    BCM_UW_COM_PLA_MODE_SET_OPCODE_E									  (84)
#define    BCM_UW_COM_PLA_FORCE_SET_OPCODE_E								  (85)
#define    BCM_UW_COM_PLA_COUNTERS_GET_OPCODE_E								  (86)
#define    BCM_UW_COM_PLA_COUNTERS_CLEAR_OPCODE_E							  (87)
#define    BCM_UW_COM_PLA_MSE_LIMIT_SET_OPCODE_E							  (88)
#define    BCM_UW_COM_PLA_PEER_DEVICE_SET_OPCODE_E							  (89)
#define    BCM_UW_COM_NET_FRAGMENTATION_SIZE_SET_OPCODE_E					  (90)
#define    BCM_UW_COM_NET_FRAGMENTATION_COUNTERS_GET_OPCODE_E				  (91)
#define    BCM_UW_COM_NET_FRAGMENTATION_COUNTERS_CLEAR_OPCODE_E				  (92)
#define    BCM_UW_COM_NET_MACFIFO_STATUS_GET_OPCODE_E						  (93)
#define    BCM_UW_COM_NET_8KHZ_MODE_SET_OPCODE_E							  (94)
#define    BCM_UW_COM_NET_8KHZ_DDS_OFFSET_GET_OPCODE_E 						  (95)

    //HC
#define    BCM_UW_COM_HC_ENGINE_ENABLE_OPCODE_E								  (96)
#define    BCM_UW_COM_HC_MASK_SET_OPCODE_E									  (97)
#define    BCM_UW_COM_HC_TYPE_SET_OPCODE_E									  (98)
#define    BCM_UW_COM_HC_LEARNING_AGEING_CONFIGURE_OPCODE_E					  (99)
#define    BCM_UW_COM_HC_DB_REFRESH_CONFIGURE_OPCODE_E						  (100)
#define    BCM_UW_COM_HC_DB_QUICK_FLUSH_OPCODE_E							  (101)
#define    BCM_UW_COM_HC_STATISTICS_GET_OPCODE_E							  (102)
#define    BCM_UW_COM_HC_PARSER_TYPE_SET_OPCODE_E                          	  (103)
#define    BCM_UW_COM_HC_PARSER_CLASS_ID_SET_OPCODE_E						  (104)

    //Peripherals
#define    BCM_UW_COM_GPIO_INT_CONFIG_OPCODE_E								  (105)
#define    BCM_UW_COM_GPIO_WRITE_OPCODE_E									  (106)
#define    BCM_UW_COM_GPIO_READ_OPCODE_E									  (107)
#define    BCM_UW_COM_AUXDAC_WRITE_OPCODE_E									  (108)
#define    BCM_UW_COM_AUXDAC_EXT_WRITE_OPCODE_E								  (109)
#define    BCM_UW_COM_AUXDAC_EXT_READ_OPCODE_E								  (110)
#define    BCM_UW_COM_AUXADC_READ_OPCODE_E									  (111)
#define    BCM_UW_COM_NET_ETH_PHY_REG_SET_OPCODE_E							  (112)
#define    BCM_UW_COM_NET_ETH_PHY_REG_GET_OPCODE_E							  (113)
#define    BCM_UW_COM_I2C_TRANSACTION_OPCODE_E								  (114)
#define    BCM_UW_COM_I2C_IS_TRANSACTION_COMPLETE_OPCODE_E 					  (115)		//removed
#define    BCM_UW_COM_SPI_TRANSACTION_OPCODE_E								  (116)
#define    BCM_UW_COM_SPI_IS_TRANSACTION_COMPLETE_OPCODE_E 					  (117)		//removed

    //Debug
#define    BCM_UW_COM_GENERAL_CONTROL_SET_OPCODE_E							  (118)	
#define    BCM_UW_COM_GENERAL_CONTROL_GET_OPCODE_E							  (119)
#define    BCM_UW_COM_DEBUG_OPCODE_E										  (120)
#define    BCM_UW_COM_REGISTER_READ_OPCODE_E								  (121)
#define    BCM_UW_COM_REGISTER_WRITE_OPCODE_E								  (122)
#define    BCM_UW_COM_INTERNAL_OPCODE_E										  (123)

    //WideBand
#define    BCM_UW_COM_WB_RX_STATUS_GET_OPCODE_E								  (124)
#define    BCM_UW_COM_WB_TX_STATUS_GET_OPCODE_E								  (125)
#define    BCM_UW_COM_WB_RX_NCO_FREQ_SET_OPCODE_E							  (126)
#define    BCM_UW_COM_WB_TX_NCO_FREQ_SET_OPCODE_E							  (127)
#define    BCM_UW_COM_WB_RX_IQ_DELAY_SET_OPCODE_E							  (128)
#define    BCM_UW_COM_WB_TXTX_SET_OPCODE_E									  (129)
#define    BCM_UW_COM_TX_TX_CALIB_STATUS_GET_OPCODE_E						  (130)
#define    BCM_UW_COM_TX_TX_CALIB_RESTART_OPCODE_E							  (131)
#define    BCM_UW_COM_WB_RX_IQMC_DELAY_SET_OPCODE_E							  (132)
#define    BCM_UW_COM_WB_RX_IQMC_DELAY_GET_OPCODE_E							  (133)
#define    BCM_UW_COM_TRANSMITTER_MODE_SET_OPCODE_E							  (134)
#define    BCM_UW_COM_WB_RX_SPECTRAL_INVERSION_SET_OPCODE_E					  (135)
#define    BCM_UW_COM_WB_SNAPSHOT_CONFIGURE_OPCODE_E						  (136)
#define    BCM_UW_COM_WB_SNAPSHOT_GET_OPCODE_E								  (137)

#define    BCM_UW_COM_WB_RX_AGC_STATUS_GET_OPCODE_E							  (138)
#define    BCM_UW_COM_WB_RX_AGC_GAIN_DIST_TABLE_SET_OPCODE_E				  (139)
#define    BCM_UW_COM_WB_RX_AGC_DB_TO_DAC_TABLE_SET_OPCODE_E				  (140)
#define    BCM_UW_COM_WB_RX_AGC_FREEZE_OPCODE_E								  (141)
#define    BCM_UW_COM_WB_RX_AGC_ROW_FORCE_OPCODE_E							  (142)

#define    BCM_UW_COM_WB_TX_AGC_STATUS_GET_OPCODE_E							  (143)
#define    BCM_UW_COM_WB_TX_AGC_CONFIGURE_OPCODE_E							  (144)
#define    BCM_UW_COM_WB_TX_AGC_TARGET_OPCODE_E								  (145)
#define    BCM_UW_COM_WB_TX_AGC_GAIN_DIST_TABLE_SET_OPCODE_E				  (146)
#define    BCM_UW_COM_WB_TX_AGC_DB_TO_DAC_TABLE_SET_OPCODE_E				  (147)
#define    BCM_UW_COM_WB_TX_AGC_ADC_TO_DBM_TABLE_SET_OPCODE_E				  (148)
#define    BCM_UW_COM_WB_TX_AGC_FREEZE_OPCODE_E								  (149)
#define    BCM_UW_COM_WB_TX_AGC_ROW_FORCE_OPCODE_E							  (150)

    //ETH Port
#define    BCM_UW_COM_ETH_PORT_INIT_OPCODE_E								  (151)
#define    BCM_UW_COM_ETH_PORT_FW_DOWNLOAD_OPCODE_E							  (152)
#define    BCM_UW_COM_ETH_PORT_CONFIGURE_OPCODE_E							  (153)
#define    BCM_UW_COM_ETH_PORT_STATUS_GET_OPCODE_E							  (154)
#define    BCM_UW_COM_ETH_PORT_COUNTERS_CLEAR_OPCODE_E						  (155)
#define    BCM_UW_COM_ETH_PORT_RX_COUNTERS_GET_OPCODE_E						  (156)
#define    BCM_UW_COM_ETH_PORT_TX_COUNTERS_GET_OPCODE_E						  (157)
#define    BCM_UW_COM_ETH_PORT_CLK_SET_OPCODE_E								  (158)

    //New 5.2
#define    BCM_UW_COM_DIG_PA_SET_OPCODE_E									  (159)
#define    BCM_UW_COM_WB_RX_AGC_SETPOINT_SET_OPCODE_E						  (160)
#define    BCM_UW_COM_WB_RX_AGC_BACKOFF_OFFSET_SET_OPCODE_E					  (161)
#define    BCM_UW_COM_WB_RX_AGC_BANDWIDTH_SET_OPCODE_E						  (162)
#define    BCM_UW_COM_PPS_CALIB_START_OPCODE_E								  (163)
#define    BCM_UW_COM_PPS_CONFIGURE_OPCODE_E								  (164)
#define    BCM_UW_COM_MIMO_CONFIGURE_OPCODE_E								  (165)
#define    BCM_UW_COM_LONG_API_PROBE_OPCODE_E								  (166)
#define    BCM_UW_COM_MODEM_IQ_SAMPLES_EX_GET_OPCODE_E						  (167)
#define    BCM_UW_COM_NET_TXMAC_FIFO_IND_SET_OPCODE_E						  (168)
#define    BCM_UW_COM_DEV_CONFIG_RESULT_GET_OPCODE_E						  (169)
#define    BCM_UW_COM_PPS_OUTPUT_MODE_SET_OPCODE_E							  (170)
#define    BCM_UW_COM_TX_TX_DELAY_SET_OPCODE_E								  (171)
#define    BCM_UW_COM_TX_TX_MODE_SET_OPCODE_E								  (172)
#define    BCM_UW_COM_PPS_STATUS_GET_OPCODE_E								  (173)

    //New 5.4
#define    BCM_UW_COM_BER_COUNTERS_GET_OPCODE_E								  (174)
#define    BCM_UW_COM_BER_ENABLE_OPCODE_E									  (175)
#define    BCM_UW_COM_DEV_CONFIG_PARAM_MODIFY_OPCODE_E						  (176)
#define    BCM_UW_COM_DEV_CONFIG_START_OPCODE_E								  (177)
#define    BCM_UW_COM_XPIC_TO_FDD_SET_OPCODE_E								  (178)
#define    BCM_UW_COM_MIMO_DELAY_CALIB_START_OPCODE_E						  (179)
#define    BCM_UW_COM_MIMO_DELAY_CALIB_STATUS_GET_OPCODE_E					  (180)
#define    BCM_UW_COM_MODEM_DELAY_GET_OPCODE_E								  (181)
#define    BCM_UW_COM_NET_ASYM_DELAY_GET_OPCODE_E							  (182)
#define    BCM_UW_COM_ADPD_GEAR_SHIFT_SET_OPCODE_E							  (183)
#define    BCM_UW_COM_WB_RX_AGC_TABLE_OFFSET_SET_OPCODE_E					  (184)

    //New 5.5
#define    BCM_UW_COM_ASYMMETRY_CONFIG_EN_OPCODE_E							  (185)
#define    BCM_UW_COM_AVS_PROCESS_SET_OPCODE_E								  (186)
#define    BCM_UW_COM_AVS_STATUS_GET_OPCODE_E								  (187)
#define    BCM_UW_COM_AVS_REC_LVM_GET_OPCODE_E								  (188)
#define    BCM_UW_COM_ETH_PORT_FW_DOWNLOAD_HDR_OPCODE_E						  (189)
#define    BCM_UW_COM_ADPD_AUTO_MODE_CONFIGURE_OPCODE_E						  (190)
#define    BCM_UW_COM_ADPD_SYSTEM_FREEZE_OPCODE_E							  (191)
#define    BCM_UW_COM_ADPD_STATUS_GET_OPCODE_E								  (192)
#define    BCM_UW_COM_MODEM_IQ_SAMPLES_SOURCE_SET_OPCODE_E					  (193)
#define    BCM_UW_COM_DEV_CONFIG_STRING_PARAM_MODIFY_OPCODE_E				  (194)
#define    BCM_UW_COM_TXRXOP_STATUS_GET_OPCODE_E							  (195)

    //New 5.6
#define    BCM_UW_COM_XPIC_DELAY_CALIBRATION_START_OPCODE_E					  (196)
#define    BCM_UW_COM_XPIC_DELAY_CALIBRATION_STATUS_GET_OPCODE_E			  (197)
#define    BCM_UW_COM_MIMO_DIVERSITY_MUTE_SET_OPCODE_E						  (198)
#define    BCM_UW_COM_WB_RX_AGC_BACKOFF_COMPENSATION_SET_OPCODE_E			  (199)
#define    BCM_UW_COM_TX_RX_CTRL_SET_OPCODE_E								  (200)

    //New 5.7
#define    BCM_UW_COM_MODEM_RX_FREQ_LIMIT_SET_OPCODE_E						  (201)
#define    BCM_UW_COM_MRC_DELAY_CALIB_START_OPCODE_E						  (202)
#define    BCM_UW_COM_MRC_DELAY_CALIB_STATUS_GET_OPCODE_E					  (203)

    //-------
    //Flash
    //-------
#define    BCM_UW_COM_FLASH_HEADER_BURN_OPCODE_E							  (204)
#define    BCM_UW_COM_FLASH_HEADER_GET_OPCODE_E								  (205)
#define    BCM_UW_COM_FLASH_INFO_GET_OPCODE_E								  (206)
#define    BCM_UW_COM_FLASH_FW_ERASE_OPCODE_E								  (207)
#define    BCM_UW_COM_FLASH_FW_BURN_OPCODE_E								  (208)
#define    BCM_UW_COM_FLASH_FW_BURNEND_OPCODE_E								  (209)
#define    BCM_UW_COM_FLASH_FS_FORMAT_OPCODE_E								  (210)
#define    BCM_UW_COM_FLASH_FILECHUNK_PUT_OPCODE_E							  (211)
#define    BCM_UW_COM_FLASH_FILECHUNK_GET_OPCODE_E							  (212)
#define    BCM_UW_COM_FLASH_FILE_DELETE_OPCODE_E							  (213)
#define    BCM_UW_COM_FLASH_FILE_LIST_OPCODE_E								  (214)
#define    BCM_UW_COM_FLASH_FILE_SIZE_GET_OPCODE_E							  (215)

    //-------
    //DSP
    //-------
#define    BCM_UW_COM_DSP_BOOT_LOADER_SET_OPCODE_E							  (216)
#define    BCM_UW_COM_DSP_APP_LOAD_OPCODE_E									  (217)
#define    BCM_UW_COM_DSP_SUBSYSTEM_PER_DSP_CONFIG_OPCODE_E					  (218)
#define    BCM_UW_COM_DSP_BLOCK_CONFIG_OPCODE_E								  (219)
#define    BCM_UW_COM_DSP_START_OPCODE_E									  (220)
#define    BCM_UW_COM_DSP_STOP_OPCODE_E										  (221)
#define    BCM_UW_COM_DSP_DEBUG_SET_OPCODE_E								  (222)
#define    BCM_UW_COM_DSP_DEBUG_GET_OPCODE_E								  (223)
#define    BCM_UW_COM_DSP_APP_LOAD_DONE_OPCODE_E							  (224)
#define    BCM_UW_COM_DSP_MEM_WR_OPCODE_E									  (225)
#define    BCM_UW_COM_DSP_MEM_RD_OPCODE_E									  (226)
#define    BCM_UW_COM_DSP_MAILBOX_MESSAGE_SEND_OPCODE_E						  (227)
#define    BCM_UW_COM_DSP_MAILBOX_MESSAGE_RECEIVE_OPCODE_E					  (228)

    //-------
    //RF
    //-------
#define    BCM_UW_COM_RF_INTERNAL_CONTROL_OPCODE_E         (240) //first RF opcode
#define    BCM_UW_COM_RF_ALL_INITIALIZE_OPCODE_E		   (241)
#define    BCM_UW_COM_RF_TX_STANDBY_SET_OPCODE_E		   (242)
#define    BCM_UW_COM_RF_TX_POWER_DOWN_OPCODE_E			   (243)
#define    BCM_UW_COM_RF_TX_ADPD_ENABLE_OPCODE_E		   (244)
#define    BCM_UW_COM_RF_TX_STATUS_GET_OPCODE_E			   (245)
#define    BCM_UW_COM_RF_RX_STANDBY_SET_OPCODE_E		   (246)
#define    BCM_UW_COM_RF_RX_POWER_DOWN_OPCODE_E			   (247)
#define    BCM_UW_COM_RF_RX_RSL_GET_OPCODE_E			   (248)
#define    BCM_UW_COM_RF_RX_STATUS_GET_OPCODE_E			   (249)
#define    BCM_UW_COM_RF_RX_TX_LOOPBACK_SET_OPCODE_E	   (250)
#define    BCM_UW_COM_RF_LO_SHARING_SET_OPCODE_E		   (251)
#define    BCM_UW_COM_RF_PROGRESS_ERROR_GET_OPCODE_E	   (252)
#define    BCM_UW_COM_RF_REGISTER_READ_OPCODE_E			   (253)
#define    BCM_UW_COM_RF_REGISTER_WRITE_OPCODE_E		   (254)

    //last one
#define    BCM_UW_COM_MAX_OPCODE_E   					   (255) //has to be <256

#define    BCM_UW_COM_OPCODE_ENUM				   unsigned char


#endif //HOST_PROTOCOL_OPCODES_H

